### ISSUE TITLE
with_unit_tests - may not be relevant

### ISSUE THREAD

**Issue by solvingj** [sigmoidal/conan-icu#5]
From the perspective of the packaging process, the unit tests seem irrelevant and unnecessary, and running them is unlikely to provide value.  Since the recipe is over 400 lines long, i would remove everything related to unit_tests in favor of a simpler shorter recipe.

**Comment by sigmoidal** [comment]
It's optional and doesn't affect package id. It's one line of code and it is very useful for potential developers of the recipe to automate building ICU and testing it. It is also recommended by ICU upstream developers to run ICU tests when building the library.
